[package]
name = "recuperator"
version = "0.1.0"
authors = ["Vincent Milano <vincent_mot@hotmail.fr>", "Valentin Fries <contact@fries.io>"]

[dependencies]
tomorrow-core = {git = "https://github.com/tomorrow-paper/tomorrow-core"}